name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: foo

    - uses: actions/setup-python@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ubuntu-latest

    - name: Upgrade pip; install requirements
      run: |
        python -m pip install --upgrade pip pytest-cov

    - name: Run pytest
      working-directory: foo
      run: pytest --color=yes . --cov .

    - uses: khaeru/coverage-gh@main
      with:
        data-file: foo/.coverage
        token: ${{ github.token }}
